### ISSUE TITLE
parallel -B -x is broken

### ISSUE THREAD

**Issue by QuLogic** [juhp/fbrnch#11]
```
$ fbrnch parallel -B -h
Usage: fbrnch parallel [-n|--dry-run] [-t|--target TARGET] ([-b|--branch BRANCH]
                       | [-B|--all-branches] | [-x|--exclude-branch BRANCH])

...
  -x,--exclude-branch BRANCH
                           branch
...
```
but
```
$ fbrnch parallel -B -x master
Invalid option `-x'

Usage: fbrnch [--version] COMMAND
  This tool helps with updating and building package branches
```
or
```
$ fbrnch parallel -B --exclude-branch master
Invalid option `--exclude-branch'

Usage: fbrnch [--version] COMMAND
  This tool helps with updating and building package branches
```

This works though:
```
$ fbrnch parallel -x master
Building parallel 3 branches:
f33 f32 f31
```

It's not noted that `-B` and `-x` are exclusive, but the error message should probably be different.

**Comment by juhp** [comment]
Yes that's right, `-B`, `-x`, and `-b` are currently exclusive.

I agree that `-B -x ..` could be useful and may add support for it.

Not sure if I can improve the error message easily - let me see/think on that:
the option handling is provided by the `optparse-applicative` library which while not perfect is quite nice.

**Comment by juhp** [comment]
> fbrnch parallel -B -h

I agree this could be confusing but basically this is equivalent to `fbrnch parallel --help`.
Help doesn't take any given options into account.

**Comment by QuLogic** [comment]
> I agree this could be confusing but basically this is equivalent to `fbrnch parallel --help`.
> Help doesn't take any given options into account.

Oh, sorry, I didn't mean to be calling that out specifically, just that `-x` didn't mention exclusivity.

**Comment by juhp** [comment]
To clarify better (also I feel optparse-applicative could lay out options better)

```
([-b|--branch BRANCH]
                       | [-B|--all-branches] | [-x|--exclude-branch BRANCH])
```

Is meant to imply that -b, -B, and -x are all exclusive.

**Comment by juhp** [comment]
(Also just a early historical note: that originally fbrnch defaulted to `-B` for all commands essentially, but I decided to make it an option tn not be too surprising/big a change compared to fedpkg.)
