### ISSUE TITLE
fbrnch create-review requires a directory?

### ISSUE THREAD

**Issue by QuLogic** [juhp/fbrnch#12]
I thought it used to accept spec files? But with 0.5-1.fc32, if I run `fbrnch create-review R-brio.spec`, it says:
```
fbrnch: No such directory: R-brio.spec
```
though the file is there.

**Comment by QuLogic** [comment]
Updated to 0.5-3.fc32, and it still does something like this.

So I moved the file into a subdirectory of `~/rpmbuild/SPECS` and it worked better, but not quite right. It created the srpm in `~/rpmbuild/SRPMS` (a bit unexpected though fine), but then after openin a Review Request, it started all over again.

**Comment by juhp** [comment]
(One can run `fbrnch create-review` without an argument to use the current directory.)

You mean you want to create packages out of `SPECS/`?
Let me think a little on this.

I often wonder about whether to use the rpmbuild default `~/rpmbuild` or not. Currently fbrnch just follows one's default settings for non-distgit: personally I override rpmbuild to use the current directory.

**Comment by QuLogic** [comment]
Well, in 0.4, it was possible to specify a file and work on that. I have tons of stuff in `SPECS`, so picking the first file out of there doesn't work at all.

**Comment by juhp** [comment]
spec filepaths should be supported now in the latest copr build.

**Comment by QuLogic** [comment]
Yep, working again.
