### ISSUE TITLE
request-repo comments are not added to bugs

### ISSUE THREAD

**Issue by QuLogic** [juhp/fbrnch#13]
The output from `request-repos` says it's adding a comment to the bug:
```
$ fbrnch request-repos R-pak
R-pak
Review Request: R-pak - Another Approach to Package Installation (ASSIGNED)
https://bugzilla.redhat.com/show_bug.cgi?id=1883047

https://pagure.io/releng/fedora-scm-requests/issue/29327
Comment added:
Thank you for the review

https://pagure.io/releng/fedora-scm-requests/issue/29327
comment added to review
```
but if I go look at the bug, no comment was added. It also says 'commend added' twice.

**Comment by juhp** [comment]
Hmm I might have noticed this myself too...
Not completely sure why this stopped working.

**Comment by juhp** [comment]
I think this was due to me "overzealously" following the bz API which says use PUT for updating bugs,
but apparently that doesn't seem to work with request body at least, which does sound right admittedly.
