### ISSUE TITLE
Don't background `parallel` for a single package

### ISSUE THREAD

**Issue by QuLogic** [juhp/fbrnch#17]
With the mass rebuild going on, I've been wondering why my builds are taking _forever_ to even start, and I just realized it's because I used `fbrnch parallel -F` and it passes `--background`. This might make sense for a huge rebuild, but I'm just running like 2 or 3 builds.

**Comment by juhp** [comment]
Ah that's a fair point - maybe there should be some threshold for this (actually Fedora Koji seems to have quite a lot of capacity).
Maybe `--background` should/could even be optional hmm.

**Comment by juhp** [comment]
(I totally agree doing it for a single package is a no-brainer.)

**Comment by juhp** [comment]
Also btw (only related but) the next release should have a `build --no-prompt` option if that helps.

**Comment by juhp** [comment]
I think I will go with the following: 
- parallel single package builds will be without --background always as you suggest
- also if there are no more than 5 concurrent packages in a parallel layer, they will also be at default priority.

I think these should give reasonable behavior in most use-cases. An override option _could_ also be added, but I am not very keen.
