### ISSUE TITLE
fbrnch import should optionally do mock builds before requesting branches

### ISSUE THREAD

**Issue by davide125** [juhp/fbrnch#18]
Akin to `fbrnch request-branches -m`, it'd be useful to have the option to do mock builds before requesting branches when importing (e.g. by adding a `--mock` to `import`). Additionally, it'd be useful to be able to prepopulate the list of branches (e.g. with a `--branches` option).

**Comment by juhp** [comment]
That's a good idea, I think, thanks

**Comment by juhp** [comment]
The 0.7.3 release has `import --mock`.

The other to changes should be in the next release,
since I would like to do more testing of `request-repos` with branches.

**Comment by juhp** [comment]
If you want to test though I can do a copr build sooner or
you can build locally with `stack install` or `cabal-install/cabal-rpm`, etc.
