### ISSUE TITLE
Remove check for git repo in parallel

### ISSUE THREAD

**Issue by QuLogic** [juhp/fbrnch#19]
I have all my packages (for a given topic) as submodules in a parent repo. This stops `fbrnch parallel` from working because it checks for a git repo in the current directory, and then stops.

**Comment by juhp** [comment]
Could you give an example (maybe a short shell script to setup a simple version of a case like this)?
Then I can try to play with it.

**Comment by QuLogic** [comment]
For example, I have all my R packages as submodules here: https://pagure.io/fedora-r-specs; I can't run `fbrnch parallel pkg1 pkg2` because of the outer git directory.

**Comment by juhp** [comment]
Anyway I see your point I guess I can try to remove this restriction.

I was curious though if you really meant they are git subsmodules?

One problem is that currently my clever branch/package selection logic assumes packages should not be inside a dist-git dir.
But I can probably do better.

**Comment by juhp** [comment]
I haven't actually tested, but I believe this should work now in HEAD and coming 0.8.0

**Comment by juhp** [comment]
> For example, I have all my R packages as submodules here: https://pagure.io/fedora-r-specs; I can't run `fbrnch parallel pkg1 pkg2` because of the outer git directory.

Ah I see, impressive!

**Comment by juhp** [comment]
I had forgotten to test your use-case before releasing 0.8.0, but it does seem to work for me.
