### ISSUE TITLE
bugzilla authentication doesn't work if you use FAS OpenID

### ISSUE THREAD

**Issue by troycurtisjr** [juhp/fbrnch#23]
I tried multiple iterations to authenticate to bugzilla: FAS + FAS Password, FAS + API Key, email + FAS password, email + API Key. Unfortunately none worked. After talking with Jens, it seems this isn't currently implemented. I did successfully use an API Key using the `python-bugzilla-cli` package, so that seems like a viable alternative which could be implemented.

**Comment by juhp** [comment]
Sorry about that - thanks for reporting this important issue.

**Comment by juhp** [comment]
I think we discussed this on irc and you were looking for bugzilla API key login iirc,
which I do plan to support but unfortunately I don't have time to do it yet.

I think logging into bugzilla with FAS requires Oauth iiuc, which fbrnch doesn't support yet sadly.

**Comment by juhp** [comment]
The coming release should have API key support (which is the only supported API authentication from next month).

**Comment by juhp** [comment]
I just released fbrnch-1.0.0 which has initial support for bugzilla API key authentication via bugzilla-redhat-1.0.0.
It should make it way into Rawhide and Fedora updates this week - would welcome any testing.

**Comment by juhp** [comment]
I am going to go ahead and close this out since API key authentication is now the only allowed way to access the REST API.
