### ISSUE TITLE
Adding %autorelease support

### ISSUE THREAD

**Issue by LyesSaadi** [juhp/fbrnch#24]
Hello again :D!

So, I switched some of my packages over to `%autorelease`, and fbrnch seems unfortunately not to support that. Indeed, it tries to build for release 1 every time `%autorelease` is set.

**Comment by juhp** [comment]
Thanks for the report. I am also slowly trying switching some of my packages over...
If you have any example builds, that would not hurt to see though.
Anyway I will try to look into it.

**Comment by juhp** [comment]
Did you mean for `fbrnch local` or `fbrnch build`?
For the former at least I think it is expected: though some workaround might be possible.

**Comment by LyesSaadi** [comment]
It was for badwolf. You didn't see the build because I did an error in 1.2.0-1, tried to fix it by submitting 1.2.0-2 as an empty commit, which failed as fbrnch refused to submit it, saying 1.2.0-1 was already built, and then had to submit 1.2.0-3 fixing everything (adding changelog entries to explain the update) and then submitted it through fedpkg.

**Comment by juhp** [comment]
Thanks for the explanation, that helps a lot.

**Comment by michel-slm** [comment]
Looking forward to a release that supports this! Coupled with #25 I think I'll have to postpone using `fbrnch` for my parallel builds

**Comment by juhp** [comment]
Okay thanks for the poke - a new release is long overdue.

Still hoping to get it out this month...

**Comment by juhp** [comment]
[fbrnch-1.0.0](https://hackage.haskell.org/package/fbrnch-1.0.0) is out now btw and coming shortly to Fedora.

**Comment by juhp** [comment]
It is in updates-testing and development releases now.

**Comment by juhp** [comment]
I am adding a few more rpmautospec fixes in the next coming release,
which I hope will be out soonish.

After that I will probably close this, but do please report any more issues you see.

**Comment by juhp** [comment]
I released 1.1
