### ISSUE TITLE
[Suggestion] create-review and update-review: Disable scratch builds by default

### ISSUE THREAD

**Issue by farchord** [juhp/fbrnch#43]
This is just a suggestion, but with Fedora's auto build system now going through all the review requests, could we set a default behavior to disable automatic scratch builds on new review submissions and updates?

Or at least allow an option to be set to change the behavior locally.

**Comment by juhp** [comment]
Good idea thanks

**Comment by juhp** [comment]
I have been thinking about this a little one and off in the back of my head...
Your suggestion certainly makes some sense, on the other hand
having the koji scratch build sanity check before uploading still seems attractive to me,
though I agree that the review auto building provides more (later).
IWBNI fbrnch could trigger that directly instead perhaps - though not sure how yet.
I feel earlier feedback is always more useful:
another alternative could be to trigger a local mock build instead of koji scratch.

To date I have hesitated to add a config file for fbrnch but it will probably be needed sooner or later.

**Comment by farchord** [comment]
To be honest, right now I've mostly just always been feeding in the -S parameter. Maybe a question:

"Would you like to perform a scratch build? (Y/N)"

Once you implemented configuration files, maybe it could remember the choice.

**Comment by farchord** [comment]
I would also argue that doing a mockbuild instead is probably not the best of ideas as, usually, when you create a package you have to do it a couple times anyway to make sure everything works. You invoke fbrnch once that's done to create the review, it's not really necessary.

Proving that your package builds is a good idea though, but with the Fedora-review-bot working now isn't it redundant?

**Comment by juhp** [comment]
Well the thing is you may have under-specified deps for example (installed locally) - anyway I take your overall point.

A prompt is probably reasonable compromise right I feel.

**Comment by farchord** [comment]
> Okay I have code for this too, which I can push soon
> 
> Do scratch build failures show up in bz with the automated builds btw?

In 99% of cases, I don't do scratch builds so I couldn't tell you. I've mostly used fbrnch for KF6 packages which was pretty cut and dry and easily reviewed. And I always locally mockbuild.

**Comment by juhp** [comment]
Okay I was asking for the automated builds...

**Comment by juhp** [comment]
Okay I pushed a [review request](https://bugzilla.redhat.com/show_bug.cgi?id=2244987) today: https://copr.fedorainfracloud.org/coprs/g/fedora-review/fedora-review-2244987-ghc-text-icu/build/6546489/

So yes it does show whether the copr build succeeded: the worse thing is that it is only built for x86_64
so without the koji build there is no way to know that it will succeed on other archs (until after approved?).

This makes me think maybe a prompt is more appropriate after all.
Well for noarch packages the copr build is sufficient I think.

**Comment by juhp** [comment]
This is in just released [1.3.3](https://hackage.haskell.org/package/fbrnch-1.3.3)
