### ISSUE TITLE
RFE: Clone packages of a group

### ISSUE THREAD

**Issue by Enchufa2** [juhp/fbrnch#46]
I would like to be able to clone all packages of a group instead of a user.

**Comment by juhp** [comment]
Aha nice idea, that shouldn't too hard

**Comment by juhp** [comment]
Seems something like `GET /api/0/group/some_group_name?projects=1&acl=commit` should work

Looking at https://pagure.io/api/0/#groups-tab

**Comment by juhp** [comment]
I implied added the API to pagure-hs in https://github.com/juhp/pagure-hs/commit/46f850cd2004e68308f4f09062dd0ae5eba92046

**Comment by Enchufa2** [comment]
> Seems something like `GET /api/0/group/some_group_name?projects=1&acl=commit` should work
> 
> Looking at https://pagure.io/api/0/#groups-tab

Yes, I've been doing this manually and it works. I intended to put this here but then slipped my mind, apologies.

**Comment by juhp** [comment]
Next step I released [pagure-cli-0.2.2](https://hackage.haskell.org/package/pagure-cli-0.2.2)
which now has a `group` command to list packages under a group.

I will build it for Fedora, but hopefully that helps a bit.

**Comment by juhp** [comment]
This included in just released fbrnch-1.5: hope you can try it out soon

**Comment by Enchufa2** [comment]
Thanks!
