### ISSUE TITLE
Run `request-repos` as part of `import`

### ISSUE THREAD

**Issue by LecrisUT** [juhp/fbrnch#55]
This would make the post-review process a one-command operation. Might need to handle waiting for repo and branches to finish

**Comment by juhp** [comment]
Ah, well I just implemented the opposite hmm: ie in the coming release `request-repos` offers to `import`.

Though I see your point in the sense that `import` might be thought to the next or main step.
In which sense they could be combined like that hmm.
Though import doing request-repo might be less obvious for seasoned packagers...

**Comment by LecrisUT** [comment]
I think that would also be ok. And I guess if you want to exit from it before the `import` you can just `ctrl+C` at the prompt for `import`. This would also be ok imo
