### ISSUE TITLE
RFE: add --suggestion for bodhi updates

### ISSUE THREAD

**Issue by LecrisUT** [juhp/fbrnch#61]
There are various settings that can be set for a bodhi update: Type, Severity, Suggestion. Would be nice when we submit an update, especially for a side-tag one to also specify those fields. Most of them would be filled manually, but the `Type: New package` could be automated if all components are a new import.

**Comment by juhp** [comment]
I have some simple logic for New package, maybe it only works for `build`.

(I presume you have seen `--update-type`.)

**Comment by juhp** [comment]
Actually --severity already exists too.  I hardly every use "reboot/restart suggestion".

**Comment by LecrisUT** [comment]
Oh, I must have missed this one as well :shrug:. Indeed the necessary fields are already implemented
