### ISSUE TITLE
fbrnch build should take update options

### ISSUE THREAD

**Issue by QuLogic** [juhp/fbrnch#7]
Since `fbrnch build` creates an update for non-Rawhide, it should take options for the update, e.g., bugs to reference and update type. (Though I guess for the former I could start putting that in the changelog.)

**Comment by juhp** [comment]
You are right - currently `build` reads bugs from the rpm changelog
(I feel it is good practice and helpful to reference bugs there),
but yeah I can add an option for reference bugs.
There may be cases where one only wants a bug per package say, I think that will be harder to handle without interactive input.
It may well be good to add this to parallel too - maybe when switching it to use sidetags by default.

**Comment by juhp** [comment]
I haven't tested this end-to-end but believe it should work (Haskell types:-)
