### ISSUE TITLE
Doesn't understand submodule repos

### ISSUE THREAD

**Issue by QuLogic** [juhp/fbrnch#8]
I have a bunch of package repos as submodules of an outer repo. When repo data is merged into the parent repo, this means the `.git` is a file, not a directory.

`fbrnch build` does not understand this, and says `fbrnch: Not a pkg git dir:`.

You can do this absorbing git dirs on a submodule:
```
$ git init
$ fedpkg clone package-name
$ git submodule add ssh://pkgs.fedoraproject.org/rpms/package-name
$ git submodule absorbgitdirs
$ cat package-name/.git
gitdir: ../.git/modules/package-name
```

**Comment by juhp** [comment]
I tested this very lightly, which suggests it seems to work afaict.

**Comment by juhp** [comment]
fbrnch-0.2-6 is built now in Copr

**Comment by QuLogic** [comment]
Updated, ran on a new package update, and it seems to be working
