### ISSUE TITLE
Creates update even on build failure

### ISSUE THREAD

**Issue by QuLogic** [juhp/fbrnch#9]
Running `fbrnch build -b f32 -m` and eventually I got:
```
2020-08-08 13:15:27,829 [ERROR] koji: ReadTimeout: HTTPSConnectionPool(host='koji.fedoraproject.org', port=443): Read timed out. (read timeout=43200)
```
but instead of re-trying or failing, it prompted for an update message and tried to create a Bodhi update. (Everything seems down now, so it seems to have not done anything.)

**Comment by juhp** [comment]
I think the real solution here is probably to stop using the python koji client.

Though supposedly this was [fixed](https://bugzilla.redhat.com/show_bug.cgi?id=1741854).

**Comment by juhp** [comment]
I am going to try a change where I ignore the koji exit code and check the taskstate always.
I hope this will improve the situation - if it is really a koji bug we should report it upstream.

**Comment by juhp** [comment]
I hope this change might prevent this problem from occurring.

`fbrnch-0.4-1` is built now in Copr.
